apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432 # cluster içerisindeki postgresql servis portu
      targetPort: 5432 # pod içinde gideceği port
      nodePort: 30007 # 30000 ile 32767 arasında olmalıdır
  selector:
    app: postgres
